# Generated by Django 5.1.2 on 2024-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='o',
            field=models.BooleanField(default=False),
        ),
    ]
