# Generated by Django 5.1.2 on 2024-10-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
